name: zulhijaya_task_project
description: Created by zulhijaya.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  get: ^4.6.3
  dio: ^4.0.6
  flutter_form_builder: ^7.1.1
  form_builder_validators: ^8.1.1
  google_fonts: ^2.3.2
  shared_preferences: ^2.0.15
  json_serializable: ^6.2.0
  flutter_overlay_loader: ^2.0.0
  intl: ^0.17.0

dev_dependencies:
  flutter_driver:
    sdk: flutter
  flutter_test:
    sdk: flutter
  build_runner: ^2.1.4
  test: ^1.21.1


  flutter_lints: ^2.0.0

flutter:

  uses-material-design: true